name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sharke-indices-bot:${GITHUB_SHA::8}
    - name: Deploy the Docker image
      run: |
        docker login docker.pkg.github.com -u matheusbsilva -p ${{ secrets.GITHUB_TOKEN }}
        docker tag sharke-indices-bot:${GITHUB_SHA::8} docker.pkg.github.com/sharke-insights/sharke-indices-bot/sharke-indices-bot:${GITHUB_SHA::8}
        docker tag sharke-indices-bot:${GITHUB_SHA::8} docker.pkg.github.com/sharke-insights/sharke-indices-bot/sharke-indices-bot:latest
        docker push docker.pkg.github.com/sharke-insights/sharke-indices-bot/sharke-indices-bot:${GITHUB_SHA::8}
        docker push docker.pkg.github.com/sharke-insights/sharke-indices-bot/sharke-indices-bot:latest
